{% set version = "0.1.14" %}

package:
  name: setuptools-gettext
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/setuptools-gettext/setuptools_gettext-{{ version }}.tar.gz
  sha256: 43f099eff31a4712cdfbcbb07e0264b0546ed3ebfd7ea998189326c519390d2c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - tomli

test:
  imports:
    - setuptools_gettext
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/breezy-team/setuptools-gettext
  summary: Setuptools gettext extension plugin
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - danielnachun
