schema_version: 1

context:
  version: "0.1.17"

package:
  name: setuptools-gettext
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/setuptools-gettext/setuptools_gettext-${{ version }}.tar.gz
  sha256: 9d292ec6fd6f567c226c8ea35440c7cbd8a51be44c8f87423bcda07eec26fe59

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - setuptools
  run:
    - python >=${{ python_min }}
    - setuptools
    - tomli

tests:
  - python:
      imports:
        - setuptools_gettext
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: Setuptools gettext extension plugin
  license: GPL-2.0-or-later
  license_file: COPYING
  homepage: https://github.com/breezy-team/setuptools-gettext

extra:
  recipe-maintainers:
    - danielnachun
